# Generated by Django 3.1.1 on 2020-09-04 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
