# Generated by Django 3.1.1 on 2020-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200904_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='amount_spent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='delta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
